permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: bottle
  email: 380094758@qq.com

# 站点信息
title: 瓶子的博客
description: My personal blog
url: /

# gavatar头像及Favicon
gavatar: /public/img/icon.jpg
favicon: /public/img/icon.jpg

# 主题设置，自动激活某个标签
active: 读书

# 首页除了最新文章外显示分类
cates: 
  - Optimization
  - LaTeX

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档